export const Actions = {
  GET_DEPTOS_REQUEST: 'GET_DEPTOS_REQUEST',
  GET_DEPTOS_SUCCESS: 'GET_DEPTOS_SUCCESS',
  DEPTO_SELECTED: 'DEPTO_SELECTED',
  SUBMIT_ALQUILER_REQUEST: 'SUBMIT_ALQUILER_REQUEST',
  SUBMIT_ALQUILER_SUCCESS: 'SUBMIT_ALQUILER_SUCCESS',
  RAISE_ERROR: 'RAISE_ERROR'
};

export const DESC_4_DIAS = 5;
export const DESC_15_DIAS = 15;
export const DESC_CLIENTE_EXISTENTE = 5;
